# Generated by Django 4.0.2 on 2022-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
