# Generated by Django 4.0.2 on 2022-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
